### ISSUE TITLE
package installation bug

### ISSUE THREAD

**Issue by tdbennett** [dewittpe/pccc#19] opened 2017-08-04 17:19 UTC
`pccc` will not build from source or install from github on Windows or OSX currently. I believe this is related to how we are requiring `Rcpp` and `dplyr`. I'm exploring this and will update.

**Comment by tdbennett** [comment] 2017-08-04 20:04
On Windows:

> devtools::install_github("dewittpe/pccc", build_vignettes = TRUE)
Downloading GitHub repo dewittpe/pccc@master
from URL https://api.github.com/repos/dewittpe/pccc/zipball/master
Installing pccc
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD  \
  build  \
  "C:\Users\bennette\AppData\Local\Temp\RtmpaUDO10\devtools252849e094c\dewittpe-pccc-7e51727"  \
  --no-resave-data --no-manual 

* checking for file 'C:\Users\bennette\AppData\Local\Temp\RtmpaUDO10\devtools252849e094c\dewittpe-pccc-7e51727/DESCRIPTION' ... OK
* preparing 'pccc':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
Warning: running command '"C:/PROGRA~1/R/R-34~1.0/bin/x64/Rcmd.exe" INSTALL -l "C:\Users\bennette\AppData\Local\Temp\Rtmp0S7R6S\Rinst59078d9539" --no-multiarch "C:/Users/bennette/AppData/Local/Temp/Rtmp0S7R6S/Rbuild59070b658b6/pccc"' had status 1
      -----------------------------------
* installing *source* package 'pccc' ...
** libs
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG  -I"C:/Users/bennette/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -I../inst/include -DARMA_64BIT_WORD   -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG  -I"C:/Users/bennette/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -I../inst/include -DARMA_64BIT_WORD   -O2 -Wall  -mtune=core2 -c ccc.cpp -o ccc.o
ccc.cpp: In function 'Rcpp::DataFrame ccc_mat_rcpp(Rcpp::CharacterMatrix&, Rcpp::CharacterMatrix&, int)':
ccc.cpp:21:9: warning: statement has no effect [-Wunused-value]
   for (i; i < dx.nrow(); ++i) { 
         ^
ccc.cpp:21:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (i; i < dx.nrow(); ++i) { 
             ^
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG  -I"C:/Users/bennette/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -I../inst/include -DARMA_64BIT_WORD   -O2 -Wall  -mtune=core2 -c get_codes.cpp -o get_codes.o
get_codes.cpp: In function 'Rcpp::List get_codes(int)':
get_codes.cpp:85:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(i=0; i<dx.length(); ++i) {
             ^
get_codes.cpp:88:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(i=0; i<pc.length(); ++i) {
             ^
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG  -I"C:/Users/bennette/Documents/R/win-library/3.4/Rcpp/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"  -I../inst/include -DARMA_64BIT_WORD   -O2 -Wall  -mtune=core2 -c pccc.cpp -o pccc.o
c:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o pccc.dll tmp.def RcppExports.o ccc.o get_codes.o pccc.o -LC:/PROGRA~1/R/R-34~1.0/bin/x64 -lRlapack -LC:/PROGRA~1/R/R-34~1.0/bin/x64 -lRblas -lgfortran -lm -lquadmath -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.0/bin/x64 -lR
RcppExports.o:RcppExports.cpp:(.rdata+0x738): undefined reference to `pccc_ccc_mat_rcpp'
RcppExports.o:RcppExports.cpp:(.rdata+0x750): undefined reference to `pccc_get_codes'
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'pccc'
* removing 'C:/Users/bennette/AppData/Local/Temp/Rtmp0S7R6S/Rinst59078d9539/pccc'
      -----------------------------------
ERROR: package installation failed
Installation failed: Command failed (1)

**Comment by tdbennett** [comment] 2017-08-04 20:07
On MacOS 12 (Sierra):

devtools::install_github("dewittpe/pccc", build_vignettes = TRUE)
Downloading GitHub repo dewittpe/pccc@master
from URL https://api.github.com/repos/dewittpe/pccc/zipball/master
Installing pccc
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD build  \
  '/private/var/folders/rs/qlthhxs51t38smdxcrfkfsn80000gn/T/RtmpGCwZKJ/devtools91d65d30ebf/dewittpe-pccc-7e51727'  \
  --no-resave-data --no-manual 

* checking for file ‘/private/var/folders/rs/qlthhxs51t38smdxcrfkfsn80000gn/T/RtmpGCwZKJ/devtools91d65d30ebf/dewittpe-pccc-7e51727/DESCRIPTION’ ... OK
* preparing ‘pccc’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
      -----------------------------------
* installing *source* package ‘pccc’ ...
** libs
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I/usr/local/include  -I../inst/include -DARMA_64BIT_WORD -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I/usr/local/include  -I../inst/include -DARMA_64BIT_WORD -fPIC  -Wall -g -O2 -c ccc.cpp -o ccc.o
ccc.cpp:21:8: warning: expression result unused [-Wunused-value]
  for (i; i < dx.nrow(); ++i) { 
       ^
1 warning generated.
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I/usr/local/include  -I../inst/include -DARMA_64BIT_WORD -fPIC  -Wall -g -O2 -c get_codes.cpp -o get_codes.o
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I/usr/local/include  -I../inst/include -DARMA_64BIT_WORD -fPIC  -Wall -g -O2 -c pccc.cpp -o pccc.o
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o pccc.so RcppExports.o ccc.o get_codes.o pccc.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
installing to /private/var/folders/rs/qlthhxs51t38smdxcrfkfsn80000gn/T/RtmpclFXlg/Rinsta3a79eaefa/pccc/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘pccc’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/private/var/folders/rs/qlthhxs51t38smdxcrfkfsn80000gn/T/RtmpclFXlg/Rinsta3a79eaefa/pccc/libs/pccc.so':
  dlopen(/private/var/folders/rs/qlthhxs51t38smdxcrfkfsn80000gn/T/RtmpclFXlg/Rinsta3a79eaefa/pccc/libs/pccc.so, 6): Symbol not found: _pccc_ccc_mat_rcpp
  Referenced from: /private/var/folders/rs/qlthhxs51t38smdxcrfkfsn80000gn/T/RtmpclFXlg/Rinsta3a79eaefa/pccc/libs/pccc.so
  Expected in: flat namespace
 in /private/var/folders/rs/qlthhxs51t38smdxcrfkfsn80000gn/T/RtmpclFXlg/Rinsta3a79eaefa/pccc/libs/pccc.so
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/private/var/folders/rs/qlthhxs51t38smdxcrfkfsn80000gn/T/RtmpclFXlg/Rinsta3a79eaefa/pccc’
      -----------------------------------
ERROR: package installation failed
Installation failed: Command failed (1)

**Comment by tdbennett** [comment] 2017-08-04 20:12
`make install` approach works on MacOS 12

**Comment by dewittpe** [comment] 2017-08-08 16:41
I've made a few small edits and have been able to successful install on windows.  @tdbennett, please verify that you can install via `devtools::install_github` on windows.

**Comment by tdbennett** [comment] 2017-08-08 22:36
Builds fine on Mac OS 12 now. Will check Windows.

**Comment by tdbennett** [comment] 2017-08-09 21:28
Builds fine with Windows locally and using `install_github` with `build_vignettes = FALSE`. Errors building with vignettes = TRUE.

**Comment by tdbennett** [comment] 2017-08-09 21:40
Error building with `vignettes = TRUE`:

```
In read.dcf(dfile, keep.white = .keep_white_description_fields) :
  cannot open compressed file 'C:/Users/bennette/AppData/Local/Temp/Rtmp4GVMTL/Rbuild574118ce97/pccc/DESCRIPTION', probable reason 'Permission denied'
Execution halted
Installation failed: Command failed (1)
```

**Comment by dewittpe** [comment] 2017-08-09 22:03
I cannot reproduce the error on my windows machine.  My session info:

```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.2.1      compiler_3.4.1  R6_2.2.2        tools_3.4.1     withr_2.0.0     curl_2.8.1      Rcpp_0.12.12    memoise_1.1.0   knitr_1.16     
[10] git2r_0.19.0    digest_0.6.12   devtools_1.13.3
```

My thoughts for the issue you are experiencing:
1.  make sure that devtools, roxygen, Rcpp, and Rtools are all updated to the most recent versions.
2. Since the issue might be with having permission to read the file, try running R (or R Studio) as admin.  I don't really like this option but it might be needed.

**Comment by tdbennett** [comment] 2017-08-10 16:11
R, Rtools, and all packages updated. More information and session info below. I'll keep looking for a solution. Weird that it's the vignettes. Miktex is in the path.

```* creating vignettes ...Warning: running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' had status 1
 ERROR
Error: file 'C:/Users/bennette/AppData/Local/Temp/Rtmp026lXi/Rbuild186861581fd/pccc/DESCRIPTION' is not in valid DCF format
In addition: Warning message:
In read.dcf(dfile, keep.white = .keep_white_description_fields) :
  cannot open compressed file 'C:/Users/bennette/AppData/Local/Temp/Rtmp026lXi/Rbuild186861581fd/pccc/DESCRIPTION', probable reason 'Permission denied'
Execution halted
Installation failed: Command failed (1)
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.2.1      compiler_3.4.1  R6_2.2.2       
 [4] tools_3.4.1     withr_2.0.0     curl_2.8.1     
 [7] Rcpp_0.12.12    memoise_1.1.0   knitr_1.17     
[10] git2r_0.19.0    digest_0.6.12   devtools_1.13.3
```

**Comment by dewittpe** [comment] 2017-08-10 16:51
During the build process, the package is built without vignettes in a temporary directory, that installation is then used to build the vignette.  After the vignettes are built, then the package is rebuilt with the vignettes.  It appears that the initial build of the package can not be accessed due to file permission issues.  

Is the error occurring on multiple windows machines?

I've added a built source `.tar.gz` of version 0.2.2 to the release and edited the README.md file to give yet another option for installing the package.

Is there any reason why this work should not be submitted to the Comprehensive R Archive Network?

**Comment by tdbennett** [comment] 2017-08-13 19:46
1. Builds/installs on another Windows machine OK - looks like it's an issue with my work machine.

Environment for which Windows install was successful:

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.2.1      compiler_3.4.1  R6_2.2.2       
 [4] tools_3.4.1     withr_2.0.0     curl_2.8.1     
 [7] Rcpp_0.12.12    memoise_1.1.0   knitr_1.17     
[10] git2r_0.19.0    digest_0.6.12   devtools_1.13.3
```

**Comment by dewittpe** [comment] 2017-10-05 04:04
I'm closing this issue, Please reopen if install errors are still an issue.

**Closed by dewittpe** 2017-10-05 04:04 UTC
Labels: bug
